In [2]:
#. Create an Array
import numpy as np
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#2. Array Operations
import numpy as np
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [6]:
#3. Maximum, Minimum & Average
import numpy as np
marks = np.array([85, 72, 91, 65, 78, 88])
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Average:", np.mean(marks))

Maximum: 91
Minimum: 65
Average: 79.83333333333333


In [8]:
#4. Even Numbers
import numpy as np
arr = np.arange(1, 21)
even = arr[arr % 2 == 0]
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
#5. Reshape an Array
import numpy as np
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
