In [2]:
#1. Create and Reshape an Array
import numpy as np
arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)


Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (4, 5)
Dimensions: 2


In [4]:
#2.Array Statistics
import numpy as np
marks = np.array([78, 85, 92, 67, 88, 95, 72, 81, 90, 76])
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Mean: 82.4
Median: 83.0
Maximum: 95
Minimum: 67


In [6]:
#3 Matrix Operations
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
print("Addition:")
print(A + B)
print("Subtraction:")
print(A - B)
print("Element-wise multiplication:")
print(A * B)

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [7]:
#4.import numpy as np

sales = np.array([
    12000, 15000, 18000, 14000,
    22000, 25000, 21000, 19000,
    28000, 30000, 27000, 32000
])
print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
highest = np.argmax(sales) + 1
lowest = np.argmin(sales) + 1
print("Highest Sales Month:", highest)
print("Lowest Sales Month:", lowest)

Total Sales: 263000
Average Sales: 21916.666666666668
Highest Sales Month: 12
Lowest Sales Month: 1
